/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/clock`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/expense`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/leave`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/time`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/clock`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/expense`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/leave`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/time`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/clock${`?${string}` | `#${string}` | ''}` | `/tabs/expense${`?${string}` | `#${string}` | ''}` | `/tabs/leave${`?${string}` | `#${string}` | ''}` | `/tabs/more${`?${string}` | `#${string}` | ''}` | `/tabs/tasks${`?${string}` | `#${string}` | ''}` | `/tabs/time${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/clock`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/expense`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/leave`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/time`; params?: Router.UnknownInputParams; };
    }
  }
}
